services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: localdevpw
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - djangonetwork

  django:
    container_name: django-api
    restart: always
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../api:/usr/src/app/api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=user
      - DB_PASS=localdevpw
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1
    working_dir: /usr/src/app/api
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    networks:
      - djangonetwork

volumes:
  postgres_data:

networks:
      djangonetwork:
          driver: bridge